In [7]:
import matplotlib.pyplot as plt
import numpy as np
import multiprocessing as mp

In [4]:
import geodesic_integrator_mp as gi

In [5]:
gi.calc_trajectory()

           message: The solver successfully reached the end of the integration interval.
           success: True
            status: 0
                 t: [ 0.000e+00  1.020e+00 ...  4.898e+01  5.000e+01]
                 y: [[ 1.000e+00  1.000e+00 ...  7.392e-01  7.390e-01]
                     [-1.000e+01 -8.979e+00 ...  3.069e+01  3.144e+01]
                     ...
                     [ 0.000e+00 -6.017e-03 ... -4.766e-01 -4.768e-01]
                     [ 5.000e+00  4.997e+00 ... -1.227e+01 -1.276e+01]]
               sol: None
          t_events: [array([], dtype=float64)]
          y_events: [array([], dtype=float64)]
              nfev: 44
              njev: 0
               nlu: 0
     hit_blackhole: False
 start_inside_hole: False

In [15]:
# a custom function that blocks for a moment
def task():
    # block for a moment
    sleep(1)
    # display a message
    print('This is from another process')

In [17]:
# create a process
process = mp.Process(target=task)

In [18]:
# run the process
process.start()

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/vries001/opt/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/vries001/opt/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'task' on <module '__main__' (built-in)>


In [20]:
def double(a):
    return a * 2

def driver_func():
    PROCESSES = 4
    with mp.Pool(PROCESSES) as pool:
        params = [(1, ), (2, ), (3, ), (4, )]
        results = [pool.apply_async(double, p) for p in params]

        for r in results:
            print('\t', r.get())
driver_func()

Process SpawnPoolWorker-106:
Process SpawnPoolWorker-109:
Process SpawnPoolWorker-108:
Process SpawnPoolWorker-107:
Traceback (most recent call last):
  File "/Users/vries001/opt/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/vries001/opt/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/vries001/opt/anaconda3/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/vries001/opt/anaconda3/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
Traceback (most recent call last):
Traceback (most recent call last):
AttributeError: Can't get attribute 'double' on <module '__main__' (built-in)>
  File "/Users/vries001/opt/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/vries001/opt/anaconda3/lib/python3.9/multiprocessin

KeyboardInterrupt: 